
const gamesData = [
  {
    id: "65478",
    title: "Sprunki Space Challenge",
    description: "In this exciting online game, kids can blast off into space and take to the skies to save the day. By hitting a speeding space car or falling rocket, players can jump into the air and start taking out enemy spacecraft. With special abilities at their disposal, they can rack up points and show off their skills. The game is free to play and offers a fun and challenging experience for kids.",
    instructions: "Arrow keys to move",
    url: "https://html5.gamemonetize.com/yy4pfievspcushsqlvr86bm9jjluq60g/",
    category: "Hypercasual",
    tags: "Avoid, Boys, Collecting, Fun, HTML5, Hypercasual, Kids, Physics, Space, Spaceship, Sprunki",
    thumb: "https://img.gamemonetize.com/yy4pfievspcushsqlvr86bm9jjluq60g/512x384.jpg",
    width: "1920",
    height: "1080"
  },
  {
    id: "65615",
    title: "Kitty Kuro Lab Escape",
    description: "Kitty Kuro is escaping from the laboratory and she needs your help. You must help Kitty Kuro. Be very careful — the doctor is holding a syringe, and if he catches you, he'll inject you. While escaping from the laboratory, you must collect all the antidotes. Don't forget — never escape without taking the card that opens the door. Use the card to unlock the door and escape from the laboratory.",
    instructions: "Press the WASD keys to move There are 4 different costumes available Playable on both mobile and PC Escape from the doctor and reach the door",
    url: "https://html5.gamemonetize.com/0meu8c86qrcjr50eeox0uzk6xy93gh0l/",
    category: "Arcade",
    tags: "1 Player, Adventure, Arcade, Cat, Girl, Girls, Hello Kitty",
    thumb: "https://img.gamemonetize.com/0meu8c86qrcjr50eeox0uzk6xy93gh0l/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65139",
    title: "Escape from School: Hellish Teacher!",
    description: "Youve entered the Strictest School in the World! Evil Teacher Mr. MeanieHead hates his students! Can you escape? Challenges, parkour, catch up, obby! Roblox!",
    instructions: "PC WASD Digital or arrows mouse Phone Joystick Buttons on the screen",
    url: "https://html5.gamemonetize.com/2rv392rx86yjbl4zz5aefk82w51a7gyh/",
    category: "Adventure",
    tags: "1 Player, 3D, 3D Games, Android, Escape, Fun, Funny, Granny, jump, Jumping, roblox, run, running, School",
    thumb: "https://img.gamemonetize.com/2rv392rx86yjbl4zz5aefk82w51a7gyh/512x384.jpg",
    width: "1920",
    height: "1080"
  },
  {
    id: "65629",
    title: "Toy Claw Simulator",
    description: "Toy Claw Simulator is a fun and addictive arcade game where you take control of a virtual claw machine to collect a wide variety of adorable toys! Carefully aim and time your claw to grab plushies, action figures, and surprise collectibles. Once youve stocked up your toy inventory, head over to the factory to sell them for shiny coins! Use your earnings to run the machine to use the crane to unlock new toys. Its a charming blend of skill, strategy, and rewarding progression!",
    instructions: "Desktop Use WASD or Arrow keys to move the crane Spacebar to grab a toy Mobile Touch and move your finger to move the crane Click to red button to grab a toy",
    url: "https://html5.gamemonetize.com/f15co4i47og2xj3qc10oe77l69ga8f6n/",
    category: "Arcade",
    tags: "3D, 3D Games, Arcade, Casual, Machine, Physics, Puzzle, Simulation, Simulator",
    thumb: "https://img.gamemonetize.com/f15co4i47og2xj3qc10oe77l69ga8f6n/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "63821",
    title: "Aidan in Danger",
    description: "Aidan in Danger is an exciting platformer where you play as Aidan, a young red-haired elf armed with a slingshot. Your mission is to protect Drakor, the last dragon on Earth, from an interdimensional villain bent on world domination. Battle dangerous monsters, travel through time, and navigate challenging levels in this epic adventure. With immersive gameplay, stunning graphics, and a gripping story, help Aidan save Drakor and restore peace to the land!",
    instructions: "AD left and right arrow keys move to the left and right W up arrow key jump C K roll X J shoot Space dash P Tab pause",
    url: "https://html5.gamemonetize.com/2zfo9lcezs29bmcw1zh6q0w62ws8upkt/",
    category: "Arcade",
    tags: "Arcade, Jumping, Pixel, Platform, Shooting",
    thumb: "https://img.gamemonetize.com/2zfo9lcezs29bmcw1zh6q0w62ws8upkt/512x384.jpg",
    width: "800",
    height: "450"
  },
  {
    id: "65128",
    title: "Candy Cutter Saga",
    description: "Candy Cutter Saga is a sweet and exciting physics-based puzzle game where precision is key! Cut the rope strategically to guide the delicious candy through tricky obstacles, collect all the stars, and land it perfectly into the mouth of the hungry player object. With challenging levels, realistic physics, and fun mechanics, Candy Cutter Saga will test your timing and problem-solving skills. Can you master every cut and feed the sweetest treats? Play now and enjoy this addictive candy-filled adventure!",
    instructions: "Plan and use your brain to cut the rope",
    url: "https://html5.gamemonetize.com/wvkxvnqi8xg8dvya4g99jhs4xvabit49/",
    category: "Puzzle",
    tags: "Best Games, Brain, Puzzle, Strategy",
    thumb: "https://img.gamemonetize.com/wvkxvnqi8xg8dvya4g99jhs4xvabit49/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65282",
    title: "Repo And Repo",
    description: "repo and repo, is a puzzle platform game where you need to switch characters in order to pick up all the gems.",
    instructions: "Control Buttons Up arrow Jump Right arrow move right left arrow move left X switch characters",
    url: "https://html5.gamemonetize.com/wkcu4chj6mfm1rgs2mmggf2b3mv047x8/",
    category: "Puzzle",
    tags: "2 Player Games, Brain, Funny, Pixel",
    thumb: "https://img.gamemonetize.com/wkcu4chj6mfm1rgs2mmggf2b3mv047x8/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65630",
    title: "Multi Theme Clicker Game",
    description: "Explore the Multi Theme Clicker Game—a tap-powered adventure across unique worlds like Pizza Empire! Rack up slices, boost your click value, unlock auto-clickers, and earn achievements. Prestige to climb higher and faster. Web Dev <a href='https://www.crazygamesx.com/'>https://www.crazygamesx.com/</a>",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/889q6ak2ni2t13zv9h6t96udazb6gjj7/",
    category: "Arcade",
    tags: "Click, Clicker, HTML5, Mentolatux",
    thumb: "https://img.gamemonetize.com/889q6ak2ni2t13zv9h6t96udazb6gjj7/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "63638",
    title: "Glass Quest",
    description: "Glass Quest – Fill the Cup, Beat the Level! Drop colorful balls into the glass and fill it up to complete each level! Be careful—every mistake costs a life. Watch your aim and timing to keep the balls in the glass. Fun, simple, and addictive puzzle gameplay awaits. Precision-based fun Five lives per level Quick and casual gameplay Can you fill the glass without spilling a single drop?",
    instructions: "Desktop Click to drop balls into the glass Fill the glass without missing or spilling balls Mobile Tap the screen to release balls Fill the glass without missing or spilling balls",
    url: "https://html5.gamemonetize.com/wnrsd26rnghr8ne2gkr41vkvmt6low6x/",
    category: "Puzzle",
    tags: "Casual, HTML5, html5 games, Hypercasual, NapTech Games, Puzzle, Skill",
    thumb: "https://img.gamemonetize.com/wnrsd26rnghr8ne2gkr41vkvmt6low6x/512x384.jpg",
    width: "1080",
    height: "1920"
  },
  {
    id: "65251",
    title: "Traffic Parking",
    description: "Traffic Parking is a challenging car puzzle game where you guide a vehicle home by navigating around obstacles like other cars and rocks. Strategize to clear paths and unlock tricks for tricky levels.",
    instructions: "Touch the car to see the car rsquo s path touch again to drive the car",
    url: "https://html5.gamemonetize.com/gyf04mppkiq7jw4lz6r441s5qiu8m7pm/",
    category: "Puzzle",
    tags: "2D, Cars, Logic",
    thumb: "https://img.gamemonetize.com/gyf04mppkiq7jw4lz6r441s5qiu8m7pm/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "62162",
    title: "Clean health Center",
    description: "Players play the role of cleaners in the health center in the game. They are responsible for the cleaning and sanitation work in all areas within the health center, keeping the environment of the health center clean and hygienic and providing a good environment for clients. The game features a fresh and lovely art style, with the details of characters and buildings depicted vividly, bringing players a healing visual enjoyment. With rich and diverse gameplay content and the freedom to construct in a large scene, players can build the health center in their minds. As players level up, they can unlock more peripheral facilities and buildings.",
    instructions: "There is a variety of cleaning tasks including common cleaning jobs such as sweeping the floor mopping the floor wiping surfaces and disposing of garbage Different areas have their corresponding cleaning tasks and requirements When cleaning players",
    url: "https://html5.gamemonetize.com/nqs5og2kxf7ukjdrqr4giqw43u4axirm/",
    category: "Hypercasual",
    tags: "Best Games, build, builder, Cartoon, Cute, html5 games",
    thumb: "https://img.gamemonetize.com/nqs5og2kxf7ukjdrqr4giqw43u4axirm/512x384.jpg",
    width: "750",
    height: "1334"
  },
  {
    id: "65624",
    title: "Squareking of Summer",
    description: "We've reached the hottest time of summer in the Squareking series. Yes, summer has arrived—and so have the dangers of summer. Watch out for the square crabs; they rule the entire beach. There are obstacles everywhere. Collect all the coins and reach the golden chest at the end of the level. You must be very careful—there are traps and enemies all around. Escape from them as quickly as you can. Web Dev <a href='https://www.dokiyo.com/'>https://www.dokiyo.com/</a>",
    instructions: "You can move using the WASD keys Mobile controls are available Collect all the Coin and reach the chest",
    url: "https://html5.gamemonetize.com/1bq3p4znfytsz80f57d829bov0lpe04y/",
    category: "Arcade",
    tags: "1 Player, 2D, Arcade, Cool, Geometry, Summer",
    thumb: "https://img.gamemonetize.com/1bq3p4znfytsz80f57d829bov0lpe04y/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64912",
    title: "Mahjong Connect Fish World",
    description: "Mahjong Connect Fish World is an innovative matching puzzle game that combines an ocean world theme with classic mahjong tile gameplay. In a dreamy underwater world, players connect matching mahjong tiles to rescue adorable sea creatures, experiencing a relaxing and entertaining puzzle adventure.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/cnhieqxamyo8vs366v5jitx9l70gwpsu/",
    category: "Puzzle",
    tags: "Board",
    thumb: "https://img.gamemonetize.com/cnhieqxamyo8vs366v5jitx9l70gwpsu/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65258",
    title: "Super Pop Blast",
    description: "Get ready for a new kind of brick shooter! Clear all the blocks using a limited number balls. Plan your moves, use the score combo system, and try to get 3 stars! - 50 handcrafted levels - Unique mechanics - Colorful aesthetics - Challenging gameplay",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/wxg2dnofcexds1qzqxw0xqdt83asu5hb/",
    category: "Puzzle",
    tags: "1 Player, 2D, Arcade, Bounce, Bricks, Bubble Shooter, Casual, Puzzle, puzzleblock",
    thumb: "https://img.gamemonetize.com/wxg2dnofcexds1qzqxw0xqdt83asu5hb/512x384.jpg",
    width: "1280",
    height: "720"
  },
   {
    id: "65563",
    title: "Banana Quest",
    description: "Get ready for a thrilling jungle adventure in Banana Quest! Play as a brave monkey on a mission to collect as many bananas as possible while dodging spikes, jumping over obstacles, and avoiding enemies. With vibrant graphics, catchy music, and smooth controls, this endless runner offers nonstop action and excitement. The more bananas you collect, the higher your score climbs! Perfect for players of all ages—simple to play, hard to master!",
    instructions: "Desktop Press the left button of the mouse to jump the Monkey Mobile Tap the screen to jump the Monkey",
    url: "https://html5.gamemonetize.com/f0t5gpi68odchy744s4u3hgdfeyqgqdu/",
    category: "Hypercasual",
    tags: "Action, Clicker, HTML5, html5 games, Hypercasual, NapTech Games, Platform",
    thumb: "https://img.gamemonetize.com/f0t5gpi68odchy744s4u3hgdfeyqgqdu/512x384.jpg",
    width: "1080",
    height: "1920"
  },
  {
    id: "65970",
    title: "Getting Over It Unblocked",
    description: "Start the most wonderful climbing adventure ever at Getting Over It Unblocked. This game will test your patience, skill, and determination like never before. You play as a man stuck in a giant pot, armed with only a hammer to climb impossible platforms. Your goal is to keep going up. Three different adventures are waiting to challenge you. Note hollowed-out platforms, longer distances, etc.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/99gjodm9l46o7lbkuf26qhc54pxyzp1o/",
    category: "Adventure",
    tags: "Fun, jump, Skill",
    thumb: "https://img.gamemonetize.com/99gjodm9l46o7lbkuf26qhc54pxyzp1o/512x384.jpg",
    width: "1920",
    height: "1080"
  },
  {
    id: "65982",
    title: "FantasticLandia",
    description: "Welcome to FantasticLandia, a world full of wonder and excitement! Jump through vibrant landscapes, solve fun challenges, and have endless hours of fun as you explore every corner!",
    instructions: "wasd space",
    url: "https://html5.gamemonetize.com/drrktlmcefmg76eh077p4hwfo4kitnz2/",
    category: "Adventure",
    tags: "1 Player, 2D, Adventure",
    thumb: "https://img.gamemonetize.com/drrktlmcefmg76eh077p4hwfo4kitnz2/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65864",
    title: "Rogue Seas Adventure",
    description: "Set sail with a fearless straw-hat kid and his rubber-quick reflexes in Rogue Seas Adventure! Hop between tiny islands, rescue captured crewmates, and stack your power before the final clash with the swampy sea-boss. Draw the perfect path, grab hidden treasure chests, and watch your elastic hero's strength skyrocket from 5 → 9 → ∞—all in snappy, one-minute puzzle rounds. Dream of becoming the next great Pirate King? This is your first step. Gather your crew, sharpen your instincts, and rule the rogue seas!",
    instructions: "Tap islands to add their numbers to yours mdash stack the biggest total and crush the boss",
    url: "https://html5.gamemonetize.com/b7fi1enampkyavtm4pg1vi7v4kt1o5bl/",
    category: "Hypercasual",
    tags: "Action, attack, Math, Puzzle, Stickman",
    thumb: "https://img.gamemonetize.com/b7fi1enampkyavtm4pg1vi7v4kt1o5bl/512x384.jpg",
    width: "600",
    height: "960"
  },
  {
    id: "65869",
    title: "Jump Redball",
    description: "A little game made by your familys beloved game developer, where you try to last as long as possible by jumping on platforms without falling on the saws.",
    instructions: "Just left and right arrow or A and D keys",
    url: "https://html5.gamemonetize.com/nnm3u3j7bwq15wctrznyhi60nzirnlgx/",
    category: "Arcade",
    tags: "2D, Arcade, Platform, survival",
    thumb: "https://img.gamemonetize.com/nnm3u3j7bwq15wctrznyhi60nzirnlgx/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65911",
    title: "Battle Tung Tung Sahur 2Player",
    description: "Are you ready for the battle of the Tung Tung Sahurs? Two teams are fighting each other, and the one who reaches the chest wins the game. Get ready to fight alongside your friend. Hit your opponent with the sticks and win the game. The player who stays at the chest the longest will be the winner. To win the game, you must defeat your friend.",
    instructions: "Use the WASD keys to play Press the S key to hit with the stick Use the Arrow keys to play Press the Down Arrow key to hit with the stick Stay near the chest for 20 seconds to win the game",
    url: "https://html5.gamemonetize.com/oqdhfw0lgqnslcbui0vpeyqao696j1m5/",
    category: "Action",
    tags: "1 Player, 2 Player, 2 Player Games, 2D, Action, Adventure, Arcade, Battle, Mobile, Tung Tung, Tung Tung Tung, Tung Tung Tung Sahur",
    thumb: "https://img.gamemonetize.com/oqdhfw0lgqnslcbui0vpeyqao696j1m5/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65188",
    title: "Giant Wanted Monster",
    description: "The city is being occupied by giant monsters. You, as an elite sniper, pick up your sniper gun. Defeat these crazy monsters and protect the survival of humanity. In Giant Wanted Monster, the fate of the city is at stake with every bullet. You need to use the powerful sniper weapon to shoot accurately from a distance and hit the monsters Achilles heel.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/3xlseluxd857tfjdkzpfjz8ts4its0bi/",
    category: "Arcade",
    tags: "Monster, running, Sniper, survival",
    thumb: "https://img.gamemonetize.com/3xlseluxd857tfjdkzpfjz8ts4its0bi/512x384.jpg",
    width: "1338",
    height: "650"
  },
  {
    id: "65266",
    title: "Drago Sky Quest",
    description: "Drago Sky Quest takes you on a soaring adventure through mystical skies and floating kingdoms! Play as Drago, a brave young dragon on a mission to reclaim the lost sky crystals and restore balance to the clouds. Glide through challenging aerial paths, dodge magical traps, defeat airborne enemies, and uncover ancient secrets. With vibrant graphics, smooth flight controls, and epic boss battles, every level is a breathtaking quest above the clouds. Collect upgrades, unlock new powers, and explore enchanting sky worlds. Are you ready to spread your wings and become the hero of the heavens? Take flight in Drago Sky Quest!",
    instructions: "use keyboard arrow key and mouse to play game or touch screen",
    url: "https://html5.gamemonetize.com/ezfj5fbcid9y641iojo6342dg2y7ohoa/",
    category: "Adventure",
    tags: "Animal, Arcade, Casual, Cute, Dragon",
    thumb: "https://img.gamemonetize.com/ezfj5fbcid9y641iojo6342dg2y7ohoa/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "63821",
    title: "Aidan in Danger",
    description: "Aidan in Danger is an exciting platformer where you play as Aidan, a young red-haired elf armed with a slingshot. Your mission is to protect Drakor, the last dragon on Earth, from an interdimensional villain bent on world domination. Battle dangerous monsters, travel through time, and navigate challenging levels in this epic adventure. With immersive gameplay, stunning graphics, and a gripping story, help Aidan save Drakor and restore peace to the land!",
    instructions: "AD left and right arrow keys move to the left and right W up arrow key jump C K roll X J shoot Space dash P Tab pause",
    url: "https://html5.gamemonetize.com/2zfo9lcezs29bmcw1zh6q0w62ws8upkt/",
    category: "Arcade",
    tags: "Arcade, Jumping, Pixel, Platform, Shooting",
    thumb: "https://img.gamemonetize.com/2zfo9lcezs29bmcw1zh6q0w62ws8upkt/512x384.jpg",
    width: "800",
    height: "450"
  },
  {
    id: "65139",
    title: "Escape from School: Hellish Teacher!",
    description: "Youve entered the Strictest School in the World! Evil Teacher Mr. MeanieHead hates his students! Can you escape? Challenges, parkour, catch up, obby! Roblox!",
    instructions: "PC WASD Digital or arrows mouse Phone Joystick Buttons on the screen",
    url: "https://html5.gamemonetize.com/2rv392rx86yjbl4zz5aefk82w51a7gyh/",
    category: "Adventure",
    tags: "1 Player, 3D, 3D Games, Android, Escape, Fun, Funny, Granny, jump, Jumping, roblox, run, running, School",
    thumb: "https://img.gamemonetize.com/2rv392rx86yjbl4zz5aefk82w51a7gyh/512x384.jpg",
    width: "1920",
    height: "1080"
  },
  {
    id: "64932",
    title: "Survive Squad",
    description: "Welcome to Survive Squad, a hot survival game that combines Strategy and Role-Playing. In a world full of crises, you will be the commander of the squad. Lead your Heroes against endless enemies! Use your wits and strategy to survive the battlefield. Collect and lay out your weapons in your Backpack System. Merge weapons of the same type for upgrades. Flexible match equipment to create the strongest survival warrior.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/0yqgrxkihwj8sh2ba5qsz1b5c85psi88/",
    category: "Arcade",
    tags: "Battle, endless, Strategy, survival, weapons",
    thumb: "https://img.gamemonetize.com/0yqgrxkihwj8sh2ba5qsz1b5c85psi88/512x384.jpg",
    width: "720",
    height: "1600"
  },
  {
    id: "64166",
    title: "Truck Simulator Arcade Championship",
    description: "Truck Simulator Arcade Championship is an exhilarating truck racing game that combines the intensity of high-speed competition with the precision of driving massive, powerful trucks. This game offers an action-packed arcade-style experience where players take control of different types of trucks and compete in various challenging racing events across diverse tracks and terrains. With fast-paced gameplay, dynamic environments, and fierce rivalries, Truck Simulator Arcade Championship is the ultimate test of skill, strategy, and control behind the wheel of a heavy-duty racing machine.",
    instructions: "WASD arrow keys to move",
    url: "https://html5.gamemonetize.com/tampigfifvuf28d2naypn6nchtzkmg3c/",
    category: "Racing",
    tags: "Driving, monstertruck, Truck",
    thumb: "https://img.gamemonetize.com/tampigfifvuf28d2naypn6nchtzkmg3c/512x384.jpg",
    width: "960",
    height: "600"
  },
  {
    id: "64051",
    title: "GT Formula Championship",
    description: "GT Formula Championship is an exhilarating high-speed racing game that brings the thrill of Formula racing to life. Step into the driver's seat of the most powerful and technologically advanced Formula cars as you compete against elite racers on world-class tracks. With intense competition, realistic physics, and breathtaking visuals, this game delivers an adrenaline-fueled experience like no other. Realistic Formula Racing Experience GT Formula Championship is designed to immerse players in the world of professional Formula racing. Every detail, from the aerodynamics of the cars to the track surface, has been meticulously crafted to provid",
    instructions: "arrow keys to move",
    url: "https://html5.gamemonetize.com/t2k033u0g3n11gnyyur592liam2k86wc/",
    category: "Racing",
    tags: "1 Player, drifting, Driving",
    thumb: "https://img.gamemonetize.com/t2k033u0g3n11gnyyur592liam2k86wc/512x384.jpg",
    width: "960",
    height: "600"
  },
  {
    id: "64176",
    title: "Space Drift",
    description: "Space Drift is an exciting hyper-casual game where players control a spaceship drifting through an asteroid field. Navigate skillfully, avoid obstacles, and collect power-ups to survive as long as possible. With smooth touch controls and dynamic gameplay, Space Drift offers an addictive challenge for players of all ages!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/ptpfgufd9fttcxygkoxilnq6exe1rbvw/",
    category: "Racing",
    tags: "airplane, Hypercasual, Pixel",
    thumb: "https://img.gamemonetize.com/ptpfgufd9fttcxygkoxilnq6exe1rbvw/512x384.jpg",
    width: "720",
    height: "1280"
  },
  {
    id: "61455",
    title: "Checkers for two",
    description: "Play classic checkers. Plan your moves and try to beat the computer or your opponent. The application may be interesting for fans of checkers and useful for beginners who want to improve their game. You can play together against each other, or against the computer (there are several levels of computer difficulty).",
    instructions: "To make a move click or click on the checker and then click or click on the next cell All moves should be made towards the edge of the opponents board you can only walk on black squares You can walk diagonally Jumping over the opponents checkers",
    url: "https://html5.gamemonetize.com/o8szudiez7aflkkdocuvs7z8o3xeawfh/",
    category: "Sports",
    tags: "2 Player, 2 Player Games, 3D, 3D Games, Brain, Casual, Educational, Family, Fun, Logic, Logical, Matching, Memory, Play",
    thumb: "https://img.gamemonetize.com/o8szudiez7aflkkdocuvs7z8o3xeawfh/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "66066",
    title: "Princess Doll Dress Up Beauty",
    description: "Welcome to Princess Doll Dress Up Beauty - a casual princess simulation game. Here you can freely create the most beautiful doll in the world. If you are a fashion and beauty lover, you will definitely feel familiar with all the items in the game. From hair design to dress up, from choosing fashionable clothes to matching different accessories, you are a styling master to design a unique fashion character!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/ba61ju4zxm7s4ergucae5tmberlk7t6t/",
    category: "Hypercasual",
    tags: "Design, Dress Up, Fashion, Simulation",
    thumb: "https://img.gamemonetize.com/ba61ju4zxm7s4ergucae5tmberlk7t6t/512x384.jpg",
    width: "1080",
    height: "1920"
  },
  {
    id: "65994",
    title: "Gemstone Glam",
    description: "Welcome to the fabulous world filled with sparkling gems! Here you will meet two charming princess girlfriends, Eliza and Tiara, who adore fashionable outfits and the glitter of colorful stones in fashionable outfits. Try on dresses inspired by the radiance of a diamond, the passion of a ruby, the freshness of an emerald and the mystery of an amethyst. Create shining combinations of hairstyles, dresses and accessories to transform our young princesses into real fashion queens. Be inspired by the natural beauty of gems and come up with images worthy of a fairy tale. Feel like a real stylist of the jewelry kingdom!",
    instructions: "Depending on the gaming device either a click of a computer mouse or a simple touch on touchscreens is used to control it",
    url: "https://html5.gamemonetize.com/bvghar76v4qwarolxtuugtvc15j3ytcl/",
    category: "Girls",
    tags: "Dress Up, Fashion, Hair, Makeover, Princess",
    thumb: "https://img.gamemonetize.com/bvghar76v4qwarolxtuugtvc15j3ytcl/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65901",
    title: "Trendy Casual Day Out",
    description: "Welcome to Trendy Casual Day Out. If you love picking out outfits and matching cute clothes, this game is for you. Trendy Casual Day Out lets you style a character for a relaxed day in town. You can go with jeans and sneakers, or a skirt and a fun top. Just like getting ready in real life, it's all about putting together something that feels right for the day.",
    instructions: "Left Mouse Button Click or Tap to Play",
    url: "https://html5.gamemonetize.com/yzwx6fzca37kvcj1p97iodrvg722ig1f/",
    category: "Girls",
    tags: "Cute, Dress Up, Fashion, Girls",
    thumb: "https://img.gamemonetize.com/yzwx6fzca37kvcj1p97iodrvg722ig1f/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65902",
    title: "Stylish Hip Hop Girl",
    description: "Step into the world of urban fashion and street dance with Stylish Hip Hop Girl! This addictive dress-up and rhythm game lets you design fierce outfits, style your character, and show off your best dance moves. Whether you love fashion, hip hop culture, or just fun creative games, this is your chance to express your unique swag!",
    instructions: "Left Mouse Button Click or Tap to Play",
    url: "https://html5.gamemonetize.com/6qnb4ysswo2k4rua3g5gc1awaw0nhrwn/",
    category: "Girls",
    tags: "Dress Up, Fashion, Girls",
    thumb: "https://img.gamemonetize.com/6qnb4ysswo2k4rua3g5gc1awaw0nhrwn/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64715",
    title: "Enchanted Easter Adventure",
    description: "Step into a magical springtime world in Enchanted Easter Adventure, where Lily and adorable bunny come together to celebrate Easter! This whimsical game combines storytelling, mini-puzzles, character dress-up, and holiday cheer in one unforgettable journey.",
    instructions: "Left Mouse Button Click",
    url: "https://html5.gamemonetize.com/waww5ce4lfwtd3vmq15o7ewpwf38tem6/",
    category: "Girls",
    tags: "Adventure, Easter, Kids, Puzzle, Skills",
    thumb: "https://img.gamemonetize.com/waww5ce4lfwtd3vmq15o7ewpwf38tem6/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "52677",
    title: "Couple Anime Dresser",
    description: "Couple Anime Dresser invites players into a vibrant world of fashion and creativity! Dive into many stylish options as you dress up adorable anime couples in dazzling outfits. Mix and match trendy hairstyles, chic clothing, and funky accessories to create the perfect ensemble for each pair.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/4cspk9tp97cbr0jweeordsxx9hjva5vt/",
    category: "Girls",
    tags: "Dress Up, Girls, HTML5, iPad, iPhone, Makeover, Mobile",
    thumb: "https://img.gamemonetize.com/4cspk9tp97cbr0jweeordsxx9hjva5vt/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64972",
    title: "Starry Style Dorama of Dream",
    description: "Welcome to an exciting journey into the world of Korean doramas heroes! Here you can become a stylist for two aspiring young film actors: a young actress whose heart beats to the rhythm of romantic stories, and a charismatic actor whose smile can melt even the coldest hearts. You will be able to choose from a variety of outfits, accessories and hairstyles, creating unique images that emphasize the individuality of your characters. Diving into the world of fashion and style, you will not only help young actors shine on the screen, but also reveal your creative abilities in creating images from your favorite doramas.",
    instructions: "Depending on the gaming device either a click of a computer mouse or a simple touch on touchscreens is used to control it",
    url: "https://html5.gamemonetize.com/221rvlei9yq7ruv26baa0tx2m8yr8wxc/",
    category: "Girls",
    tags: "Celebrity, Dress Up, Hair, Makeover",
    thumb: "https://img.gamemonetize.com/221rvlei9yq7ruv26baa0tx2m8yr8wxc/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64215",
    title: "Celebrity Spring Manicure Design",
    description: "Step into the glamour of 'Celebrity Spring Manicure Design'! Explore a world of trendy nail art, vibrant colors, and chic designs. Join celebrities in setting the trend for spring nails. Elevate your style with creative manicures, from floral elegance to modern motifs. Immerse yourself in the art of nail fashion and transform your fingertips into a canvas of spring-inspired beauty. Express your unique style, celebrate the season, and make your nails a fashion statement with Celebrity Spring Manicure Design!",
    instructions: "Left Mouse Button Click",
    url: "https://html5.gamemonetize.com/ch97aqxj675ukvlnvf1yscgskbsc1g26/",
    category: "Girls",
    tags: "Cute, Dress Up, Fashion, Girls",
    thumb: "https://img.gamemonetize.com/ch97aqxj675ukvlnvf1yscgskbsc1g26/512x384.jpg",
    width: "560",
    height: "854"
  },
  {
    id: "61594",
    title: "Sprunki VS Pirates",
    description: "Sprunki Vs Pirates is an exciting sports game to play for all ages. Get into this technical game that tests your aiming ability to make a goal. The challenge is simple yet thrilling: how long can you stay in the game? Your endurance is determined by how well you can aim. Calculate the right angle and degree of force and launch the Ninja through into the basket! In Sprunki Vs Pirates, you need to master the art of precision. Each level presents new obstacles and challenges, ensuring that the game remains engaging and stimulating.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/m9jlea8vrshpp1wbps50h8jhu7toajor/",
    category: "Sports",
    tags: "Basketball, mapi games, Sprunki",
    thumb: "https://img.gamemonetize.com/m9jlea8vrshpp1wbps50h8jhu7toajor/512x384.jpg",
    width: "1024",
    height: "600"
  },
  {
    id: "58502",
    title: "Mini Tennis",
    description: "This exciting arcade sports game is easy to pick up but challenging to master if youre aiming for high scores! Like in a classic tennis match, returning the balls demands speed and precision one misstep, and its game over! The longer you stay on the court, the faster the tennis balls come flying at you, and its up to you to return each one while dodging airborne bottles. Be warned: earning the Platinum medal is a true test of skill! Only those with grand slam-worthy reflexes can claim it!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/0g1lbwa9t0i9se2gx1a15f0x1j5eto2t/",
    category: "Sports",
    tags: "mapi games, Sport, Tennis",
    thumb: "https://img.gamemonetize.com/0g1lbwa9t0i9se2gx1a15f0x1j5eto2t/512x384.jpg",
    width: "768",
    height: "1024"
  },
  {
    id: "58497",
    title: "Downhill Christmas Dash",
    description: "The snow is falling and Santa Claus is hitting the slopes! He has strapped on pair of skis and is racing down the hill collecting gift boxes along the way. Race to the bottom and collect as many gifts as you can, but look out for those evil Snowmen! They are out to stop Santa from his Christmas mission. If you bump into a snowman you will fall and the game will end. There are special power-ups along the way that will help you get a higher score. The winged boots increase your speed and raise the gifts scores. The golden star make you invincible for 8 seconds. The Christmas sports game will challenge your reflexes and get you in the Christmas",
    instructions: "Use the right and left arrow key or touch the onscreen arrows to control Santas direction Collect the gifts and avoid the snowmen",
    url: "https://html5.gamemonetize.com/gy8anb0a2zg6t4mg3ey98w29x05plzw6/",
    category: "Sports",
    tags: "Christmas, Magic, Sports, surprize",
    thumb: "https://img.gamemonetize.com/gy8anb0a2zg6t4mg3ey98w29x05plzw6/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "94",
    title: "Monopoly Online",
    description: "MONOPOLY online game. It's the classic game of Monopoly that you know and love with an online twist. Relive one of the most iconic board game series of all time, the classic Business game Monopoly now online",
    instructions: "Left click to play the game",
    url: "https://html5.gamemonetize.com/rb9b7ctnmy1rjphxzuwlmy8c4b7mw9po/",
    category: "Puzzle",
    tags: "2 Player, 3D, 3D Games, Board, Boys, Girl, Girls, HTML5, Logic, Logical, Multiplayer, Puzzle",
    thumb: "https://img.gamemonetize.com/rb9b7ctnmy1rjphxzuwlmy8c4b7mw9po/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "32219",
    title: "Fire Brigade - Super Firefighter",
    description: "Fire Brigade is an interesting 3D game, you can play it both on the computer and mobile phone. There are so many people stuck in the fire, as the fire brigade, you need to save them! Drive your car and reach the destination, save all people from the fire. Enjoy the Fire Brigade!",
    instructions: "Tap or click",
    url: "https://html5.gamemonetize.com/8df6zeehotwimc7gfduuvirem450b7sr/",
    category: "Boys",
    tags: "3D, 3D Games, Boy, Boys, Fire, Fun, H5, HTML5, Kid, Kids, Superhero",
    thumb: "https://img.gamemonetize.com/8df6zeehotwimc7gfduuvirem450b7sr/512x384.jpg",
    width: "750",
    height: "1334"
  },
  {
    id: "5916",
    title: "City Bike Stunt",
    description: "It's time to show off your skills on motorcycles with the City Bike Stunt game! If you complete 6 different races in time, you can unlock powerful motorcycles. Aim for the ramps and avoid the barriers while you attempt to reach the finish line in each thrilling level. Do not forget to use NITRO power to pass long ramps! Continue with the \"2 PLAYER\" option to play with your friend. Prove to your friend who is a better motorcycle master!",
    instructions: "Player 1 Move ARROW KEYS Nitro N Camera C Player 2 Move W A S D Nitro T Camera Q Level Restart R",
    url: "https://html5.gamemonetize.com/4fsie8xlboycrf46lxevrj522e1pwmp0/",
    category: "Racing",
    tags: "2 Player, 2 Player Games, 3D Games, Adventure, Bike, gta, Motorcycle",
    thumb: "https://img.gamemonetize.com/4fsie8xlboycrf46lxevrj522e1pwmp0/512x384.jpg",
    width: "900",
    height: "500"
  },
  {
    id: "32198",
    title: "Room Escape 3D",
    description: "Room Escape 3D is an interesting puzzle online game for free. You need to use cunning means to sneak around the guards, but don't let them find you. Try to outwit the enemy! You can test your logical thinking ability in this one of the best 3D prison games. All kinds of cool action tasks and puzzles are waiting for you! The overall operation of the game is not difficult, but you need to be bold, careful, and flexible to play this game well!",
    instructions: "Mouse or tap to play",
    url: "https://html5.gamemonetize.com/plnmq55nuyrrhg29e4j660vya3ux76q3/",
    category: "Boys",
    tags: "3D, Adventure, Android, Avoid, Boy, Brain, Escape, Fun, HTML5, Kids, Obstacle, Online, Puzzle, Room",
    thumb: "https://img.gamemonetize.com/plnmq55nuyrrhg29e4j660vya3ux76q3/512x384.jpg",
    width: "750",
    height: "1334"
  },
  {
    id: "65644",
    title: "Bubble Shooter Legend 2",
    description: "Enjoy a fun shooting puzzle game in Bubble Shooter Legend. Use your shooting skills in this casual puzzle game. Your goal is to match bubbles of the same color. Make them explode and disappear to complete each level step by step. Match three or more bubbles of the same color by aiming and firing them to explode and eliminate them!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/j5q8k34qimuwm8su7zfr7i8l7i9ymzqb/",
    category: "Puzzle",
    tags: "Bubble Shooter, Funny, Matching, Skills",
    thumb: "https://img.gamemonetize.com/j5q8k34qimuwm8su7zfr7i8l7i9ymzqb/512x384.jpg",
    width: "1280",
    height: "720"
  },
  {
    id: "65117",
    title: "Planetary Plunge",
    description: "Planetary Plunge hurls you into a thrilling cosmic free-fall across the galaxy! Navigate your way through asteroid fields, dodge alien obstacles, and dive deeper into mysterious planets as you race for survival. With fast-paced action, stunning space environments, and easy one-touch controls, every plunge is a heart-racing adventure. Collect cosmic power-ups, unlock new astronaut suits, and challenge yourself with increasingly difficult worlds. Will you master the art of the perfect fall and become the ultimate space explorer? Prepare for a breathtaking descent and discover the unknown in the thrilling journey of Planetary Plunge!",
    instructions: "use arroww key on keyboard for play game darr Down arrow to light Brown uarr Upper arrow Silver larr Left arrow yellow brown rarr Right arrow dark brown",
    url: "https://html5.gamemonetize.com/fgv5a33f4ww77sgmwi48eesl3twgmx52/",
    category: "Puzzle",
    tags: "Adventure",
    thumb: "https://img.gamemonetize.com/fgv5a33f4ww77sgmwi48eesl3twgmx52/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "65366",
    title: "Worms Hungry",
    description: "worms Hungry is a puzzle game with 80 different levels. Your goal is to collect all the colored dots and paint all the tiles, but be careful! one wrong move can make you lose the game. With fun gameplay, to reach your goal you must crawl across the entire scenario! The holes are a good way to get to other places, think carefully before making a move! Thank you and have fun!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/caulq2sxnpb3ys392qxsta2uvupzuejx/",
    category: "Puzzle",
    tags: "Brain, Puzzle, Strategy, Worms",
    thumb: "https://img.gamemonetize.com/caulq2sxnpb3ys392qxsta2uvupzuejx/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64568",
    title: "Defense Designer",
    description: "Defense Designer is a strategic tower defense game where you must protect your castle against waves of relentless enemies. Build and upgrade different types of towers, construct walls, and manage your resources wisely to survive increasingly difficult challenges.",
    instructions: "Touch click to select building types and place towers Upgrade towers by clicking on them",
    url: "https://html5.gamemonetize.com/cuz9vjzfbtj01cyg3jbgqhypolcmzi5a/",
    category: "Shooting",
    tags: "1 Player, Defense, Shoot, Shooting, Strategy, Tower Defense",
    thumb: "https://img.gamemonetize.com/cuz9vjzfbtj01cyg3jbgqhypolcmzi5a/512x384.jpg",
    width: "600",
    height: "800"
  },
  {
    id: "54777",
    title: "Move n Hit Space",
    description: "Brace yourself for an epic space battle in Move n Hit - Space! Navigate your spaceship through waves of enemy ships, dodging their attacks and collecting power-ups.Test your reflexes and strategic thinking as you maneuver through increasingly challenging levels. Rack up points by surviving longer and eliminating enemies, and see how far you can go in this thrilling space adventure!",
    instructions: "Move through enemy aircrafts while shooting them The longer the survival the higher the score",
    url: "https://html5.gamemonetize.com/97dzn748xi5zuqsz28kptvfybwdjb2pp/",
    category: "Adventure",
    tags: "Aircraft, Battle, Space, Spaceship",
    thumb: "https://img.gamemonetize.com/97dzn748xi5zuqsz28kptvfybwdjb2pp/512x384.jpg",
    width: "720",
    height: "1280"
  },
  {
    id: "64721",
    title: "Monsters of Easter Eggs",
    description: "Easter has arrived. During the holiday, the Easter eggs came to life and turned into monsters. You must destroy all the eggs. Grab your weapon and start shooting. Eliminate all the egg monsters. Reach the forest portal at the end of the level. Enter the portal and fight the boss egg monster. The fate of Easter is in your hands.",
    instructions: "Use the WASD keys to move Use the mouse to shoot You can also play the game on mobile Touch controls are available Defeat all enemies beat the boss enemy and complete the level",
    url: "https://html5.gamemonetize.com/dvavq5dcfxmyfapvsrrll9ucs4c7d59v/",
    category: "Adventure",
    tags: "1 Player, Action, Arcade, Easter, egg, eggs, Gun, Shooter",
    thumb: "https://img.gamemonetize.com/dvavq5dcfxmyfapvsrrll9ucs4c7d59v/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64753",
    title: "Squad Shooter Simulation Shootout",
    description: "Want to experience the most shocking 3D FPS shooting wars? In the Squad Shooter: Simulation Shootout, lead your elite squad to victory. Enter the realistic shooting simulator, as a tactical special forces soldier on exciting combat missions. Use your gun to aim accurately and walk flexibly.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/pbqkkhkop6rk9lihboh8j4zt3zsitvy7/",
    category: "Boys",
    tags: "3D, Battle, fps, Funny, Minecraft, Shoot",
    thumb: "https://img.gamemonetize.com/pbqkkhkop6rk9lihboh8j4zt3zsitvy7/512x384.jpg",
    width: "1920",
    height: "1080"
  },
  {
    id: "64797",
    title: "Zombie City Rescue",
    description: "Zombie City Rescue is an intense action-strategy game where youre humanity's last hope! The city has fallen to the undead, and it's up to you to rescue survivors, eliminate zombies, and restore order in a world gone mad. How to play: Lead your rescue squad through zombie-infested streets. Save trapped civilians and escort them to safety. Use weapons, tools, and tactics to fight hordes of the undead. With thrilling missions, dangerous enemies, and heart-pounding action, Zombie City Rescue delivers nonstop excitement. Upgrade your squad, unlock powerful gear, and plan each rescue mission with care—every move could mean life or death.",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/k954hi27bgkdjopqz2uq8cavxplwgb9q/",
    category: "Shooting",
    tags: "1 Player, Action, Best, Best Games, Coloring, Shoot, Shooting, Zombie",
    thumb: "https://img.gamemonetize.com/k954hi27bgkdjopqz2uq8cavxplwgb9q/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "64072",
    title: "Missile Attack",
    description: "Missile Attack Game Missile Attack troops, cities and villages are under air strikes. The enemy has launched dozens of missiles! Please command your troops to destroy the missiles and save thousands of innocent lives. The people of the country are counting on you! Pick up your weapons and destroy the missiles before they land. Missile Attack is an immersive game that tests your speed. Accept the challenge, act methodically and quickly, and strive for the highest score!",
    instructions: "Mouse click or tap to play",
    url: "https://html5.gamemonetize.com/ik002uzg1oh7o1esc062q780u28y8niz/",
    category: "Adventure",
    tags: "airplane, Shoot, Shooting",
    thumb: "https://img.gamemonetize.com/ik002uzg1oh7o1esc062q780u28y8niz/512x384.jpg",
    width: "800",
    height: "600"
  },
  {
    id: "63280",
    title: "Power Slap",
    description: "Power Slap is an exciting slap battle game where timing, precision, and reflexes are the key to victory! Engage in fast-paced slap duels, test your skills, and out-slap your opponents to dominate the leaderboards. With simple one-tap controls, smooth animations, and addictive arcade-style gameplay, every match is a thrilling challenge. Unlock power-ups, upgrades, and special abilities to gain an edge in battle. Enjoy quick, casual fun anytime, whether youre playing solo or competing with friends. Do you have what it takes to become the ultimate slap master? Play now and prove your skills!",
    instructions: "Just click tap on screen",
    url: "https://html5.gamemonetize.com/zmlw34hzwakgnkd2nrr1798aqp7xzu7y/",
    category: "Hypercasual",
    tags: "1 Player, Battle, Casual, Street Fighting",
    thumb: "https://img.gamemonetize.com/zmlw34hzwakgnkd2nrr1798aqp7xzu7y/512x384.jpg",
    width: "960",
    height: "600"
  }
];

export default gamesData;